### ISSUE TITLE
existing simplesamlphp 1.14.14 installation @ /var/simplesamlphp

### ISSUE THREAD

**Issue by blooodorange** [sgomez/simplesamlphp-module-oauth2#10]
Hi,

when i try to install the module via composer (composer.phar require sgomez/simplesamlphp-module-oauth2 ~1.0) a new instance/installation of simplesamlphp is created @ /home/username/vendor/simplesamlphp/simplesamlphp

Is there an option to install the module to an existing simplesaml installation resp. to a different path?

Many thanks,
Martin

**Comment by sgomez** [comment]
Sorry, but this module must be installed inside a valid SimpleSAMLphp installation. It's not a issue of this module. It's a dependency from "simplesamlphp/composer-module-installer".
