### ISSUE TITLE
Private informations in exception

### ISSUE THREAD

**Issue by Elektordi** [sgomez/simplesamlphp-module-oauth2#16]
Hello,

Using print_r($e); in exception handling is a security problem, since the whole world can read it, and access private information in calls parameters.

You should use the integrated error reporter of simplesamlphp, which is pretty good at logging, or if you really need to display such stuff in your module, you should only do this if DEBUG is TRUE in global configuration.

It is present in those files:
https://github.com/sgomez/simplesamlphp-module-oauth2/blob/master/www/access_token.php
https://github.com/sgomez/simplesamlphp-module-oauth2/blob/master/www/authorize.php
https://github.com/sgomez/simplesamlphp-module-oauth2/blob/master/www/userinfo.php

**Comment by sgomez** [comment]
Hi again ;-)

Sorry, but this module is marked as abandoned in packagist. 

I had another development than supports oauth2 and OIDC.

https://github.com/rediris-es/simplesamlphp-module-oidc

Please, consider to use the new package.
