### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by andrius-kulbis** [sgomez/simplesamlphp-module-oauth2#2]
Maybe there are plans for including a short description of how this module works?

**Comment by sgomez** [comment]
Yes, I do. But I'm actually involved on rewriting this plugin from scratch, because it's based on out-of-maintenance library (fos/oauth2) and I prefer to use thephpleague/oauth2-server library. It's taking longer that I'd like but I'm pretty busy right now.

**Comment by andrius-kulbis** [comment]
Nice, good luck with your work.

**Comment by edelahozuah** [comment]
We have been able to deploy the current version of the module.  We can provide you with some info in case you do not want to wait for the next version of the module.

Keep up with the good work, Sergio.

From: Andrius
Reply-To: sgomez/simplesamlphp-module-oauth2
Date: Wednesday, 2September, 2015 09:07
To: sgomez/simplesamlphp-module-oauth2
Subject: [simplesamlphp-module-oauth2] Documentation (#2)

Maybe there are plans for including a short description of how this module works?

**Comment by andrius-kulbis** [comment]
Well, that would be very helpfull.
