### ISSUE TITLE
Fatal error:  Cannot redeclare class SimpleSAML_Module

### ISSUE THREAD

**Issue by disccomp** [sgomez/simplesamlphp-module-oauth2#3]
Commit #1329f63f3b1a6580c10e99924bc7ae5c327f8235
hooks/hook_frontpage.php:12
`'href' => SimpleSAML\Module::getModuleURL('oauth2/registry.php'),`

Seems to be leading to: PHP Fatal error: Cannot redeclare class SimpleSAML_Module in Module.php.

Changing this back fixes the issue.
`'href' => SimpleSAML_Module::getModuleURL('oauth2/registry.php'),`

**Comment by sgomez** [comment]
This problem is related with the same #4  issue, you need the master version of simplesamlphp. I will try to fix it ASAP.

**Comment by sgomez** [comment]
Sorry, this module was only available for SimpleSAMLphp master branch.

From now, you can use ^1.0 for SimpleSAMLphp 1.14 and ^2.0 for master branch.

Please, see the [README.md](https://github.com/sgomez/simplesamlphp-module-oauth2/blob/master/README.md) file.
