### ISSUE TITLE
Twig module not installed

### ISSUE THREAD

**Issue by disccomp** [sgomez/simplesamlphp-module-oauth2#4]
Twig is not mentioned in the README, nor does it install with composer. I'm assuming it needs to be added in one of those two places. 
However, once installed with composer, it does not seem to load the files OOTB.

Caused by: Exception: Template: Could not find template file [oauth2:registry_list] at [/srv/simplesamlphp/modules/oauth2/templates/registry_list]
Backtrace:
3 /srv/simplesamlphp/lib/SimpleSAML/XHTML/Template.php:659 (SimpleSAML_XHTML_Template::findTemplatePath)
2 /srv/simplesamlphp/lib/SimpleSAML/XHTML/Template.php:576 (SimpleSAML_XHTML_Template::show)
1 /srv/simplesamlphp/modules/oauth2/www/registry.php:39 (require)
0 /srv/simplesamlphp/www/module.php:137 (N/A)

**Comment by sgomez** [comment]
Hi @disccomp 

Yes, there is a problem with dependencies, because this plugin only works with the master version of simplesamlphp than [includes twig](https://github.com/simplesamlphp/simplesamlphp/blob/master/composer.json).

Sorry for the inconvenience.

**Comment by ajaaibu** [comment]
@sgomez Any update on the compatibility of this module with the current release of simplesamlphp?

**Comment by sgomez** [comment]
Sorry, this module was only available for SimpleSAMLphp master branch.

From now, you can use ^1.0 for SimpleSAMLphp 1.14 and ^2.0 for master branch.

Please, see the [README.md](https://github.com/sgomez/simplesamlphp-module-oauth2/blob/master/README.md) file.
