### ISSUE TITLE
How to get work with Globus Auth

### ISSUE THREAD

**Issue by plessbd** [sgomez/simplesamlphp-module-oauth2#6]
First, I might be going about this all wrong, if I am please feel free to say so and close this issue.

I currently use simpleSAMLPHP in my application and we want to use globus auth (https://docs.globus.org/api/auth/)

I was wondering if you could give me any guidance on how to set this up.

I am able to get simplesamlphp installed and setup with this module, but am uncertain on how to actually setup the authsource to be able to use globus

**Comment by sgomez** [comment]
Sorry, this module is to create an OAuth2 Server. You want to add an OAuth2 Authorization Server (Globus) as an SSP Authorization Source.

AFAIK there are not a module for this (but could be a good idea to do one).

Ask in the official mailing list support.

**Comment by plessbd** [comment]
In case anyone else cared about this we decided to build one for our project: https://github.com/ubccr/simplesamlphp-module-authglobus (it is in the process of getting code reviewed and made available)
