### ISSUE TITLE
Endless Redirect with 1.0 Version

### ISSUE THREAD

**Issue by grueneedv** [sgomez/simplesamlphp-module-oauth2#7]
Dear Gomez,

I installed the ~1.0 branch as described in the Readme at an 1.14.14 Version of SimpleSAML. After creating the database which apparantly worked out (SQLite Database file is present) its stated to configure the module on the Federation Tab. When I try to do this I get redirected so often, that the browser stops the process.
In the Serverlog I see the following for access_log
![accesslog](https://user-images.githubusercontent.com/17144683/27330648-ad78f9fa-55ba-11e7-84c0-42894f7bf267.PNG)
In error_log is nothing.
Where to start trying to debug this? I created the certs as stated and the config file I tried admin and default-sp as authentication source, both with the same result.
Before installing the plugin I could log in and out without troubles.

Regards Martin

**Comment by sgomez** [comment]
This seems more a problem with you ssp installation. If you can do the administrator login is not a issue of this plugin (because is not related).

Check your config.php file. See if you have configurated 'session.cookie.domain' with the same domain of your host (and the rest of cookie parameters).

If the problem persist, try to uninstall both modules (dbal and oauth2) and try again to do admin login.

If after uninstalling it works,  please, send me your config.php if you can.

**Comment by grueneedv** [comment]
I even can't do the admin login, which is also redirected.

session.cookie.domain was null, I tried with my domain, but again endless redirect.

When both plugins are uninstalled the installation works fine. 

I went a step back and installed only the dbal module made the change in config store.type and got the endless redirect. So the problem seems to with the dbal module. When I switch store.type back to phpsession all is working. I changed the cookie.domain from null to my domain, and it works with phpsession. Maybe close the Issue here and recreate one in dbal module?

At the end the question remains, where to start debugging this?

**Comment by grueneedv** [comment]
Okay I tracked down the problem further. The problem is with accessing the database. I changed the path of the sqlite file, now the schema is created (worked before anyways) and I don't get endless redirect, instead I get:
![erroropeningdatabase](https://user-images.githubusercontent.com/17144683/27435672-2874e83c-575d-11e7-833f-98eaa8ad18b0.PNG)
Now I'm confused. No error from DBAL Module which wrote the table with vendor/bin/dbalschema (I looked into the sqlite file) and I landed somewhere deep in Doctrine. Any hint where to go from here?

**Comment by sgomez** [comment]
Hmmm. The web server must have write permissions to the sql file. Can you confirm that?

**Comment by grueneedv** [comment]
Yes, I changed 0666 of the database file and even changed the owner to apache. Same result. Even set SELinux to permissive.

**Comment by grueneedv** [comment]
Narrowed down the problem a little further. As far as I understood first a get request is made and of course there is no entry in the sqlite database. So the result is null to SimpleSaml (line 128 here https://github.com/sgomez/simplesamlphp-module-dbal/blob/1.0/lib/SimpleSAML/Modules/DBAL/Store/DBAL.php)
After that set is called and the set function jumps into delete at line 168. Delete is building the query and executing the query but never returns so that the set function never moves on and reaches line 169. I modified line 219 from $qb->delete($this->kvstorePrefix) to $qb->delete($this->kvstorePrefix."test") which should run in the catch exception but it doesn't. I'm not that into this programming to fix this yet, any ideas? How to debug further? Is SQLite working anyways?

**Comment by grueneedv** [comment]
Tried MySQL today with the same result. Giving up on getting this working.

**Comment by sgomez** [comment]
Hi @grueneedv 

Sorry but I'm in holidays until next week. Anyway I need your config.php to replicate your environment and try to debug it.

I have this plugin in production w/o any issues.
