### ISSUE TITLE
get new access_token using refresh token

### ISSUE THREAD

**Issue by foadyousefi** [sgomez/simplesamlphp-module-oauth2#8]
Hi
I've started using this module, it just works. 

Using grant_type of code to generate new access_token, returns refresh_token also. I tried to get new access_token using grant_type of refresh_token with the same endpoint, but response was "unsupported_grant_type". 

My question is how to use refresh_token to generate new access_token. Is it even possible? If yes, how to do it, what is endpoint and which parameters should I use?

**Comment by sgomez** [comment]
Refresh token is [implemented](https://github.com/sgomez/simplesamlphp-module-oauth2/blob/2d47df410e54106c6aed92f285d3ddf27dc50074/lib/SimpleSAML/Modules/OAuth2/OAuth2AuthorizationServer.php#L56). 

You have all the information in the [OAuth2 Server Library Site](https://oauth2.thephpleague.com/authorization-server/refresh-token-grant/).

I let this issue opened until I can tested it again (I'm very busy right now).

**Comment by sgomez** [comment]
Hi @foadyousefi 

I can confirm than something is wrong with this. I hope to have time this week to solve it.

**Comment by sgomez** [comment]
Hi @foadyousefi 

This must be resolved in 1.0 and 2.0 versions.

Can you update and try it again?

**Comment by foadyousefi** [comment]
Great.
I checked it, it is working as it should.
I think it is time to close this issue.
