### ISSUE TITLE
userinfo stoped working

### ISSUE THREAD

**Issue by foadyousefi** [sgomez/simplesamlphp-module-oauth2#9]
Hi.
Today I tried to login, but had some problem. After some debugging, realised problem is 'simplesaml/module.php/oauth2/userinfo.php' endpoint. It was working perfect yesterday. 

I tried to test using postman, it returns error displayed in the image:

![pasted_image_14_07_2017__16_08](https://user-images.githubusercontent.com/19663888/28215676-197089d2-68af-11e7-9ae7-ea848fb3f591.png)

**Comment by sgomez** [comment]
Hi @foadyousefi 

It's working well for me. Can you check with curl?

```
curl -D header.log --request GET --url https://server/simplesaml/module.php/oauth2/userinfo.php --header 'authorization: Bearer TOKEN'
```

The header is processing by OAuth 2 Server library and it should work well. It's so strange that Authorization header wasn't found. Maybe some blank space and the end of the Authorization word?

**Comment by foadyousefi** [comment]
I found the problem. 
The app is in development stage and lives on dev server. For some reason .htaccess file that sets CORS configurations, was reseted and configurations was removed. But still thanks for your fast response.

In case somebody had same problem, here is my setting:
<IfModule mod_headers.c>
        RewriteCond %{HTTP:Authorization} ^(.*)
        RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
        SetEnvIf Origin "^http(s)?://(.+\.)?(domain1\.com|localhost)$" REQUEST_ORIGIN=$0
        Header set Access-Control-Allow-Origin %{REQUEST_ORIGIN}e env=REQUEST_ORIGIN
        Header set Access-Control-Allow-Methods "GET, POST, PUT, DELETE"
        Header set Access-Control-Allow-Headers: "Authorization, Content-Type"
</IfModule>

But keep in mind this is development server, in production don't add "Access-Control-Allow-Origin" for "localhost".
